### ISSUE TITLE
Issues for full-width white space

### ISSUE THREAD

**Issue by aradtamako** [dfcat/105Global#2]
# Steps to reproduce this issue

1. Open F105
https://apps.dfcat.net/f105/

2. Search item name
```
ドラゴン　スレイヤー
```

3. Not found
![image](https://user-images.githubusercontent.com/40272766/175860520-d6f449c5-cd69-46b2-819b-3efd629eeecb.png)

# Possible solution
Use half-width white space instead of full-width white space.
So, please consider to treat full-width and half-width space in the same way.(Program side)

```
ドラゴン スレイヤー
```

![image](https://user-images.githubusercontent.com/40272766/175860431-53fb43fc-2a24-422d-b017-43180db16367.png)

# Environment
- Google Chrome 103.0.5060.53

**Comment by dfcat** [comment]
Done.

convert japan space (ascii 12288) to common space (ascii 32)

query.replace(new RegExp(String.fromCharCode(12288)), ' ')
