### ISSUE TITLE
Invalid translation

### ISSUE THREAD

**Issue by aradtamako** [dfcat/105Global#3]
# Steps to reproduce this issue

1. Open F105
https://apps.dfcat.net/f105/

2. Create new preset
![image](https://user-images.githubusercontent.com/40272766/175861247-0fae1703-3e47-42ac-b376-a275ab0e939c.png)

3. Press F5 (Reload web page)

4. Invalid translation
I expected `保存する` instead of `저장`.
https://github.com/aradtamako/105Global/blob/93b17ac458a401eb604d888adc55a9990af5ad01/f105.jp.js#L26

![image](https://user-images.githubusercontent.com/40272766/175861022-beffb845-043f-478d-a82e-37fdcc86358d.png)

# Possible solution
Nothing

# Environment
- Google Chrome 103.0.5060.53

**Comment by dfcat** [comment]
Done.

problem: translate '저장' to each langs before load langs data.
fixed: render components after load all data.
